# Protocol
END_TRANSMISSION_MESSAGE = "END"
APP_ID = 1
CLIENT_ID = 0

# Criteria
LANGUAGE_CRITERIA_KEYWORD = "LANGUAGE"
EQUAL_CRITERIA_KEYWORD = "EQUAL"
CONTAINS_CRITERIA_KEYWORD = "CONTAINS"
GRATER_THAN_CRITERIA_KEYWORD = "GREATER_THAN"
EQUAL_FLOAT_CRITERIA_KEYWORD = "EQUAL_FLOAT"
