# Protocol
END_TRANSMISSION_MESSAGE = "END"
SESSION_TIMEOUT_MESSAGE = "TIMEOUT"
APP_ID = 2
MSG_ID = 1
CLIENT_ID = 0

# Criteria
EQUAL_CRITERIA_KEYWORD = "EQUAL"
CONTAINS_CRITERIA_KEYWORD = "CONTAINS"
GRATER_THAN_CRITERIA_KEYWORD = "GREATER_THAN"
EQUAL_FLOAT_CRITERIA_KEYWORD = "EQUAL_FLOAT"
