# Protocol
END_TRANSMISSION_MESSAGE = 'END' 
APP_ID = 0

# Criteria
LANGUAGE_CRITERIA_KEYWORD = 'LANGUAGE'
EQUAL_CRITERIA_KEYWORD = 'EQUAL'
CONTAINS_CRITERIA_KEYWORD = 'CONTAINS'
GRATER_THAN_CRITERIA_KEYWORD = 'GREATER_THAN'