END_TRANSMISSION_MESSAGE = 'END' 
NULL_FIELD_VALUE = ''

GAMES_APP_ID = 0
GAMES_NAME = 1
GAMES_RELEASE_DATE = 2
PLATFORMS = {
    'WINDOWS': 3, 
    'MAC': 4, 
    'LINUX': 5
}
GAMES_AVG_PLAYTIME_FOREVER = 6
GAMES_GENRE = 7 

REVIEW_APP_ID = 0
REVIEW_NAME = 1
REVIEW_TEXT = 2
REVIEW_SCORE = 3