SESSION_TIMEOUT_TRANSMISSION_MESSAGE = 'TIMEOUT'

END_TRANSMISSION_MESSAGE = 'END' 
END_TRANSMISSION_CLIENT_ID_INDEX = 0
END_TRANSMISSION_MSG_ID_INDEX = 1
END_TRANSMISSION_END_INDEX = 2 

NULL_FIELD_VALUE = ''
REVIEWS_MESSAGE_TYPE='reviews'
GAMES_MESSAGE_TYPE='games'

GAMES_SESSION_ID = 0
GAMES_MSG_ID = 1
GAMES_APP_ID = 2
GAMES_NAME = 3
GAMES_RELEASE_DATE = 4
PLATFORMS = {
    'WINDOWS': 5, 
    'MAC': 6, 
    'LINUX': 7
}
GAMES_AVG_PLAYTIME_FOREVER = 8
GAMES_GENRE = 9

REVIEW_SESSION_ID = 0
REVIEW_MSG_ID = 1
REVIEW_APP_ID = 2
REVIEW_TEXT = 3
REVIEW_SCORE = 4
