END_TRANSMISSION_MESSAGE = "END"
SESSION_TIMEOUT_TRANSMISSION_MESSAGE = "TIMEOUT"
NULL_FIELD_VALUE = ""
REVIEWS_MESSAGE_TYPE = "reviews"
GAMES_MESSAGE_TYPE = "games"

GAMES_SESSION_ID = 0
GAMES_APP_ID = 1
GAMES_NAME = 2
GAMES_RELEASE_DATE = 3
PLATFORMS = {"WINDOWS": 4, "MAC": 5, "LINUX": 6}
GAMES_AVG_PLAYTIME_FOREVER = 7
GAMES_GENRE = 8

REVIEW_SESSION_ID = 0
REVIEW_APP_ID = 1
REVIEW_TEXT = 2
REVIEW_SCORE = 3
