version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging: #para que no loggee rabbitmq
      driver: none
    healthcheck: 
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24