version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
    networks:
      - net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: none
    healthcheck: 
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - CLI_ID=1 
    volumes:
      - ./data/:/data 
    networks:
      - net 
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    
volumes:
  rabbitmq_data:

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24