name: steam_reviews_system
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 15672:15672
    networks:
    - net
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: none
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: '5'
  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
    - ./data/:/data
    networks:
    - net
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  filter_columns0:
    image: filter_columns:latest
    container_name: filter_columns0
    environment:
    - NODE_ID=0
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  filter_columns1:
    image: filter_columns:latest
    container_name: filter_columns1
    environment:
    - NODE_ID=1
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  filter_columns2:
    image: filter_columns:latest
    container_name: filter_columns2
    environment:
    - NODE_ID=2
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  filter_columns3:
    image: filter_columns:latest
    container_name: filter_columns3
    environment:
    - NODE_ID=3
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  filter_columns4:
    image: filter_columns:latest
    container_name: filter_columns4
    environment:
    - NODE_ID=4
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  drop_columns0:
    image: drop_nulls:latest
    container_name: drop_nulls0
    environment:
    - NODE_ID=0
    - COUNT_BY_PLATFORM_NODES=1
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  drop_columns1:
    image: drop_nulls:latest
    container_name: drop_nulls1
    environment:
    - NODE_ID=1
    - COUNT_BY_PLATFORM_NODES=1
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  drop_columns2:
    image: drop_nulls:latest
    container_name: drop_nulls2
    environment:
    - NODE_ID=2
    - COUNT_BY_PLATFORM_NODES=1
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  drop_columns3:
    image: drop_nulls:latest
    container_name: drop_nulls3
    environment:
    - NODE_ID=3
    - COUNT_BY_PLATFORM_NODES=1
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  drop_columns4:
    image: drop_nulls:latest
    container_name: drop_nulls4
    environment:
    - NODE_ID=4
    - COUNT_BY_PLATFORM_NODES=1
    - INSTANCES_OF_MYSELF=5
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_filter_action_games0:
    image: filter_by_column_value:latest
    container_name: q4_action_games0
    environment:
    - NODE_ID=0
    - RECIVING_QUEUE_NAME=q4_games
    - FORWARDING_QUEUE_NAME=q4_action_games
    - AMOUNT_OF_FORWARDING_QUEUES=2
    - LOGGING_LEVEL=DEBUG
    - COLUMN_NUMBER_TO_USE=2
    - VALUE_TO_FILTER_BY=action
    - CRITERIA=CONTAINS
    - COLUMNS_TO_KEEP=0,1
    - INSTANCES_OF_MYSELF=1
    - BATCH_SIZE=10
    - BROADCASTS=True
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_filter_negative0:
    image: filter_by_column_value:latest
    container_name: q4_negative0
    environment:
    - NODE_ID=0
    - RECIVING_QUEUE_NAME=q4_reviews
    - FORWARDING_QUEUE_NAME=q4_negative_reviews
    - AMOUNT_OF_FORWARDING_QUEUES=2
    - LOGGING_LEVEL=DEBUG
    - COLUMN_NUMBER_TO_USE=2
    - VALUE_TO_FILTER_BY=-1.0
    - CRITERIA=EQUAL_FLOAT
    - COLUMNS_TO_KEEP=0,1
    - INSTANCES_OF_MYSELF=1
    - BATCH_SIZE=10
    - BROADCASTS=True
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_first_counter_counter0:
    container_name: q4_first_counter_counter0
    image: counter_by_app_id:latest
    entrypoint: python3 /main.py
    environment:
    - NODE_ID=0
    - CONSUME_QUEUE_SUFIX=q4_negative_reviews
    - PUBLISH_QUEUE=q4_negative_reviews_count
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_filter_first_more_than_5000_0:
    image: filter_by_column_value:latest
    container_name: q4_first_more_than_5000_0
    environment:
    - NODE_ID=0
    - RECIVING_QUEUE_NAME=q4_negative_reviews_count
    - FORWARDING_QUEUE_NAME=q4_filter_first_more_than_5000_reviews
    - AMOUNT_OF_FORWARDING_QUEUES=1
    - LOGGING_LEVEL=DEBUG
    - COLUMN_NUMBER_TO_USE=1
    - VALUE_TO_FILTER_BY=5000
    - CRITERIA=GREATER_THAN
    - COLUMNS_TO_KEEP=0
    - INSTANCES_OF_MYSELF=1
    - BATCH_SIZE=10
    - BROADCASTS=False
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_join0:
    container_name: q4_join0
    image: join:latest
    environment:
    - INPUT_GAMES_QUEUE_NAME=0_q4_action_games
    - INPUT_REVIEWS_QUEUE_NAME=0_q4_filter_first_more_than_5000_reviews
    - OUTPUT_QUEUE_NAME=q4_first_join
    - AMOUNT_OF_BEHIND_NODES=1
    - AMOUNT_OF_FORWARDING_QUEUES=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_join1:
    container_name: q4_join1
    image: join:latest
    environment:
    - INPUT_GAMES_QUEUE_NAME=0_q4_first_join
    - INPUT_REVIEWS_QUEUE_NAME=1_q4_negative_reviews
    - OUTPUT_QUEUE_NAME=q4_second_join
    - AMOUNT_OF_BEHIND_NODES=1
    - AMOUNT_OF_FORWARDING_QUEUES=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_filter_english0:
    image: filter_by_column_value:latest
    container_name: q4_english0
    environment:
    - NODE_ID=0
    - RECIVING_QUEUE_NAME=0_q4_second_join
    - FORWARDING_QUEUE_NAME=q4_english_reviews
    - AMOUNT_OF_FORWARDING_QUEUES=1
    - LOGGING_LEVEL=DEBUG
    - COLUMN_NUMBER_TO_USE=2
    - VALUE_TO_FILTER_BY=en
    - CRITERIA=LANGUAGE
    - COLUMNS_TO_KEEP=0
    - INSTANCES_OF_MYSELF=1
    - BATCH_SIZE=10
    - BROADCASTS=False
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_second_counter_counter0:
    container_name: q4_second_counter_counter0
    image: counter_by_app_id:latest
    entrypoint: python3 /main.py
    environment:
    - NODE_ID=0
    - CONSUME_QUEUE_SUFIX=q4_english_reviews
    - PUBLISH_QUEUE=q4_english_review_count
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_filter_second_more_than_5000_0:
    image: filter_by_column_value:latest
    container_name: q4_second_more_than_5000_0
    environment:
    - NODE_ID=0
    - RECIVING_QUEUE_NAME=q4_english_review_count
    - FORWARDING_QUEUE_NAME=q4_second_filter_more_than_5000
    - AMOUNT_OF_FORWARDING_QUEUES=1
    - LOGGING_LEVEL=DEBUG
    - COLUMN_NUMBER_TO_USE=1
    - VALUE_TO_FILTER_BY=5000
    - CRITERIA=GREATER_THAN
    - COLUMNS_TO_KEEP=0,1
    - INSTANCES_OF_MYSELF=1
    - BATCH_SIZE=10
    - BROADCASTS=False
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
  q4_join2:
    container_name: q4_join2
    image: join:latest
    environment:
    - INPUT_GAMES_QUEUE_NAME=1_q4_action_games
    - INPUT_REVIEWS_QUEUE_NAME=0_q4_second_filter_more_than_5000
    - OUTPUT_QUEUE_NAME=Q4
    - AMOUNT_OF_BEHIND_NODES=1
    - AMOUNT_OF_FORWARDING_QUEUES=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - net
    restart: on-failure
volumes:
  rabbitmq_data: {}
networks:
  net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
