END_TRANSMISSION_MESSAGE = "END"
APP_ID = 0

CLIENT_INFO_QUEUE_NAME_INDEX = 0
CLIENT_INFO_CONNECTION_ID_INDEX = 1
CLIENT_INFO_LAST_MESSAGE_INDEX = 2
CLIENT_INFO_FINISHED_QUERIES_INDEX = 3
CLIENT_INFO_TIMER_INDEX = 4
CLIENT_INFO_FINISHED_QUERIES_LOCK_INDEX = 5
CLIENT_INFO_BATCH_SIZE = 6


DATA_MESSAGE_TYPE = "D"
QUERY_RESULTS_REQUEST_MESSAGE_TYPE = "Q"
HEARTBEAT_MESSAGE_TYPE = "H"
SESSION_RESTART_MESSAGE_TYPE = "C"
NEW_SESSION_REQUEST_MESSAGE_TYPE = "N"
SESSION_ACK_MESSAGE_TYPE = "A"
