[DEFAULT]
# Queues 
RECIVING_QUEUE_NAME=__REQUIRED__
FORWARDING_QUEUE_NAME=__REQUIRED__

# Dataset 
COLUMNS_TO_KEEP=__REQUIRED__
# For games: 
# 0: app_id, 
# 1: name, 
# 2: release_date, 
# 16: windows, -> Hay que sumarle 1 por un error en el dataset de aca en adelante
# 17: mac, 
# 18: linux, 
# 28: avg_playtime_forever, 
# 35: genre

# For reviews:
# 0: app_id,
# 1: app_name,
# 2: review_text, 
# 3: review_score


# Logging 
LOGGING_LEVEL=DEBUG

# Node
NODE_ID=__REQUIRED__
INSTANCES_OF_MYSELF=__REQUIRED__

# Rabbit server
RABBIT_IP=rabbitmq